# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      APIKEYS__GITHUBTOKEN: ${{ secrets.APIKEYS__GITHUBTOKEN }}
      APIKEYS__BREVOAPIKEY: ${{ secrets.APIKEYS__BREVOAPIKEY }}
      CONNECTIONSTRINGS__DEFAULTCONNECTION: ${{ secrets.CONNECTIONSTRINGS__DEFAULTCONNECTION }}
      EMAILLIST__SENDERNAME: ${{ secrets.EMAILLIST__SENDERNAME }}
      EMAILLIST__SENDEREMAIL: ${{ secrets.EMAILLIST__SENDEREMAIL }}
      EMAILLIST__RECIPIENTNAME: ${{ secrets.EMAILLIST__RECIPIENTNAME }}
      EMAILLIST__RECIPIENTEMAIL: ${{ secrets.EMAILLIST__RECIPIENTEMAIL }}
      
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
